version: 0.2

phase: 
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 cp --recursive ./build s3://www.cross-africa/
      - aws cloudfront create-invalidation --distribution-id EBCDGGYOSVD1 --path /\*